name: Test workflow on plain docker
on:
  pull_request:
    branches:
    - master
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: AOD2NanoAOD test - plain docker
    steps:
      # chmod of the script before getting to the container
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          mkdir outputs
      # run the container with the script in the repository
      - name: Going to a container
        id: container
        run: | 
          docker run -v $(pwd):/mnt/vol -w /home/cmsusr cmsopendata/cmssw_5_3_32 /bin/bash /mnt/vol/commands.sh 1000 data_cfg.py
          echo ls -l  `ls -l `
          cp output.root outputs
      # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: outputs/
